version: '1.0'
services:
  mdb:
      image: "mongo"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=passwordXXX
  bridge_app:
    build: .
    ports:
      - "3200:3200"
    environment:
      - SERVER_PORT=3200
      - NODE_ENV=dev
      - DB_USER=root
      - DB_PASS=passwordXXX
      - DB_HOST=mdb
      - DB_PORT=27017
      - DB_NAME=admin
      - JWT_CHECK=true
      - JWT_SECRET_KEY=any secret phrase
