version: '1.0'
services:
  db:
      image: "mongo"
      # volumes:
      #   - ./libs:/docker-entrypoint-initdb.d
      # environment:
      #   - MONGO_INITDB_ROOT_USERNAME=root
      #   - MONGO_INITDB_ROOT_PASSWORD=passwords
  bridge_app:
    build: .
    ports:
      - "3200:3200"
    environment:
      - SERVER_PORT=3200
      - NODE_ENV=dev
      # - DB_HOST=mongodb://root:password@db:27017/informator
      - DB_HOST=mongodb://db:27017/informator